pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('6-devops/backend-greet-service'){
                    sh './mvnw clean package'
                }
            }
        }
    }
}