pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('6-devops/backend-greet-service'){
                    sh './mvnw clean package'
                }
            }
        }
        stage('Docker build') {
            steps {
                dir('6-devops/backend-greet-service'){
                    sh 'docker build -t nagabhushanamn/backend-greet-service:latest .'
                }
            }
        }
        stage('Docker push i.e CD') {
            steps {
                dir('6-devops/backend-greet-service'){
                    sh 'docker push nagabhushanamn/backend-greet-service:latest'
                }
            }
        }
        stage('K8s deploy i.e CD') {
            steps {
                dir('6-devops/backend-greet-service'){
                    sh 'kubectl apply -f k8s/backend-greet-service.yml'
                }
            }
        }
    }
}