
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-greet-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-greet-app
  template:
    metadata:
      labels:
        app: backend-greet-app
    spec:
      containers:
      - name: backend-greet-container
        image: nagabhushanamn/backend-greet-service:latest:latest
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: backend-greet-service
spec:
  type: LoadBalancer
  selector:
    app: backend-greet-app
  ports:
    - targetPort: 8080
      port: 8080