
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accounts_db
    username: root
    password: root1234
  jpa:
    show-sql: true

transfer.limit: 2000

---

spring.config.activate.on-profile: test
transfer.limit: 3000

---

spring.config.activate.on-profile: prod
transfer.limit: 4000
